### ISSUE TITLE
how to add this to Brim MacOS version ?

### ISSUE THREAD

**Issue by mostafazaghlol** [brimdata/build-suricata#68]

**Comment by philrz** [comment]
@mostafazaghlol: Could you provide some more detail on what you're trying to achieve?

The Suricata artifact that comes out of this build repo is already part of Brim for macOS. The way it comes together is that Suricata (and Zeek) are included as analyzers in the [Brimcap](https://github.com/brimdata/brimcap) tool, and Brimcap is then bundled as part of Brim.

If you were asking because you want to do some kind of customization to the Suricata that runs with Brim, I'd not recommend working off this repo. There's a [Custom Brimcap Configuration](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config) article in the Brimcap wiki that shows how to invoke analyzers other than the ones that come bundled with the app. That would allow you to use any Suricata that runs on macOS, such as the one available via [Homebrew](https://formulae.brew.sh/formula/suricata). That article happens to use Linux as a reference point, but completing the equivalent steps on macOS should be very similar and if you have any trouble I'd be happy to field your questions here or on our [public Slack](https://www.brimdata.io/join-slack/).

I'll hold this issue open to see if you're able to provide more detail on your intentions

**Comment by philrz** [comment]
@mostafazaghlol: Since we've not heard from you since this issue was first opened back in 2022 I'm going to assume the last comment either answered your question or you've moved on to something else, so I'm going to go ahead and close this. Feel free to comment again or come talk to us on our [public Slack](https://www.brimdata.io/join-slack/) if you'd like to revisit the topic.
